apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: "Probe Service"
  name: ejemplo4
  labels:
    app: Deployejemplo4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Deployejemplo4
  template:
    metadata:
      labels:
        app: Deployejemplo4
    spec:
      containers:
      - name: ejem4deploy1
        image: python:3.6-alpine
        command: ['sh', '-c','hostname > index.html && echo "Ejemplo 4 " >> index.html && python -m http.server 80']
---
apiVersion: v1
kind: Service
metadata:
  name: servicejemplo4
  labels:
    app: Deployejemplo4
spec:
  type: ClusterIP
  selector:
    app: Deployejemplo4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

